### PR TITLE
[CLEANUP] Adding an NPM package with Hitachi Vantara's _default_ prettier configuration.

### PR DESCRIPTION
**Pull request by dcleao**
@pentaho/millenniumfalcon, @pentaho/kashyyyk, @pentaho/bobafett, @pentaho/x-wing, @diogofscmariano, @francisco-guilherme, @nantunes please review.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 18s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
Guys, I added a readme file.

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 19s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by dcleao** [comment]
@pentaho/millenniumfalcon, @pentaho/kashyyyk, @pentaho/bobafett, @pentaho/x-wing, @diogofscmariano, @francisco-guilherme, @nantunes: if no one else opposes, will be merging this in one hour from now.

**Comment by dcleao** [comment]
Delaying merge a bit more to give others from the internal quality related slack channels a chance to voice any concerns.

**Pull request merged**
