### PR TITLE
Changed the Prettier configuration to have bracket spacing.

### PR DESCRIPTION
**Pull request by andrefrua**
I was going to apply the prettier coding standards to our new project, but when I did the code started looking a bit hard to read when importing the needed modules for each component.

How it looks using the current prettier settings from _pentaho-coding-standards_ repository:
```
import React, {useEffect} from "react";
import {RouterState} from "connected-react-router";
import {useTranslation} from "react-i18next";
import HvHeader from "@hv/uikit-react-core/dist/Header";
import HvUserIcon from "@hv/uikit-react-icons/dist/Generic/User";
import HitachiLogo from "assets/hitachi-logo.svg";
import {View} from "models/views";
import {HeaderProps} from "./index";
```

How it will look with the proposed change:
```
import React, { useEffect } from "react";
import { RouterState } from "connected-react-router";
import { useTranslation } from "react-i18next";
import HvHeader from "@hv/uikit-react-core/dist/Header";
import HvUserIcon from "@hv/uikit-react-icons/dist/Generic/User";
import HitachiLogo from "assets/hitachi-logo.svg";
import { View } from "models/views";
import { HeaderProps } from "./index";
```

I believe that this is much easier to read than the first example.

Let me know what you guys think.

### CODE REVIEW

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 20s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Comment by andrefrua** [comment]
Sorry for the delay on the answer.
Regarding object literals the only visible change would be if we have object declaration in a single line.
Prior to the change we would have:
`const aaa = {bbb: "some text", ccc: "more text"}`
After the change we would have:
`const aaa = { bbb: "some text", ccc: "more text" }`

In a multi line object declaration we wouldn't see any difference because the brackets would appear on a line of their own.

As for the versioning, yes I do agree that this should be done in a major version.

**Comment by dcleao** [comment]
@andrefrua Thanks, that looks fine. I took a look and this is still in the pre-1.0 version: `0.1.0`.
So, I believe we can easily go to `0.2.0` (which is seen as a major, in pre-1.0 versions).

**Comment by buildguy** [comment]
### :white_check_mark: Build finished in 23s
Build command:
```console
mvn clean verify -B -e -Daudit -amd
```
---
 :exclamation: No tests found!
 ---
 
 

:information_source:  _This is an automatic message_

**Pull request merged**
