### PR TITLE
Added checkstyle install instructions for Visual Studio Code

### PR DESCRIPTION
**Pull request by adamfowleruk**
Added instructions for how to have checkstyle working in Visual Studio Code. Verified with recent internal Vantara projects.

### CODE REVIEW

**Comment by adamfowleruk** [comment]
I should probably mention I am a Hitachi Vantara employee in the EMEA Sales Engineering team. Email address adam dot fowler at hitachivantara dot com

**Comment by lucboudreau** [comment]
Hello Adam. Nice to meet you. Can you remove the eclipse changes? I'll gladly merge your changes to the Readme after.

**Comment by adamfowleruk** [comment]
OK think I've managed to fix that. Please let me know your thoughts.

**Comment by tmcsantos** [comment]
There's no new vs code instructions on this pr, closing it.

**Pull request closed without merging**
